version: '3.1'

services:
  backend:
    build:
      context: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      PORT: ${FRONTEND_PORT}
      NODE_ENV: production
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
