version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
